### ISSUE TITLE
Getting reporter not found error while using this reporter 

### ISSUE THREAD

**Issue by rikisudhir** [ArchitectNow/cypress-testrail-reporter#74]
Hello Team, I tried to use this as mentioned in the document. . but getting "reporter not found" error. Other cypress test rail reporter working fine for me.
Could you please take a look.

**Comment by nartc** [comment]
Lemme give the reporter a try and get back to you as soon as possible.

**Comment by nartc** [comment]
And also it would help if you could provide a reproducible repo.

**Comment by Macavity** [comment]
@nartc The issue seems to be the following, if you install this libary through npm you don't get the src but only a dist directory.
And the dist files are pretty empty. I can't tell you why it's empty though..

The package.json of the reporter contains this:
`  "main": "dist/index.js",
  "module": "dist/cypress-testrail-reporter.esm.js",`

This is the content of dist/cypress-testrail-reporter.esm.js
`
//# sourceMappingURL=cypress-testrail-reporter.esm.js.map
`

Likely something in the build went wrong.
